name: 🤙 错误报告
description: 当出现问题时提交报告以便修复！
title: '🐞 错误报告: xxx.md'
labels: ['request']
assignees: jaywcjlove
body:
  - type: markdown
    attributes:
      value: |
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧   
        注意：请求太多，参考【优先级】快速添加内容  
        🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧   

  - type: input
    id: error-list
    attributes:
      label: 错误清单
      description: 选择一个错类型
      placeholder: ex. `docs/ansible.md`

  - type: checkboxes
    id: error-type
    attributes:
      label: 错误类型
      description: 请选择一个错类型
      options:
        - label: 排版 & 文字错误
        - label: 清单内容示例错误
        - label: 其它

